"""
Streamlit UI for RAG Case Study

This application allows searching for similar documents stored in Pinecone
and summarizing them using the Groq LLM (llama-3.1-8b-instant).

- Embeddings: HuggingFace all-MiniLM-L6-v2 (free, local)
- Vector Store: Pinecone
- LLM (summaries): Groq (fallback if Pinecone search itself isn't enough)

Usage:
    streamlit run 3-ui.py
"""

import os
import streamlit as st
from dotenv import load_dotenv
from langchain_pinecone import PineconeVectorStore
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_groq import ChatGroq
from langchain_core.documents import Document

load_dotenv()


# ---------------------------------------------------------------------------
# Helper: Embeddings
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner="Loading embedding model...")
def create_embeddings(model_name: str = "BAAI/bge-large-en-v1.5") -> HuggingFaceEmbeddings:
    """Create and cache HuggingFace embeddings (free, runs locally).

    Cached with st.cache_resource so the model is loaded only once per session.

    Args:
        model_name (str): HuggingFace sentence-transformer model name.

    Returns:
        HuggingFaceEmbeddings: Configured embeddings instance.
    """
    return HuggingFaceEmbeddings(
        model_name=model_name,
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True}
    )


# ---------------------------------------------------------------------------
# Helper: Pinecone similarity search
# ---------------------------------------------------------------------------
def search_similar_documents(
    query: str,
    no_of_results: int = 3,
    index_name: str = None,
    embeddings: HuggingFaceEmbeddings = None
) -> list:
    """Search Pinecone for documents similar to the given query.

    Args:
        query (str): The search query / job description.
        no_of_results (int): Number of results to return.
        index_name (str): Pinecone index name. Defaults to env variable.
        embeddings (HuggingFaceEmbeddings): Embeddings to use. Creates one if None.

    Returns:
        list: List of (Document, score) tuples.

    Raises:
        ValueError: If query is empty.
    """
    if query is None or query.strip() == "":
        raise ValueError("Query must be a non-empty string.")

    if index_name is None:
        index_name = os.getenv("PINECONE_INDEX_NAME")

    if embeddings is None:
        embeddings = create_embeddings()

    pinecone_api_key = os.getenv("PINECONE_API_KEY")
    vector_store = PineconeVectorStore(
        index_name=index_name,
        embedding=embeddings,
        pinecone_api_key=pinecone_api_key,
    )

    results = vector_store.similarity_search_with_score(query, k=no_of_results)
    return results


# ---------------------------------------------------------------------------
# Helper: Groq LLM summary
# ---------------------------------------------------------------------------
def get_summary_from_llm(resume_document: Document) -> str:
    """Generate a concise summary of a resume document using Groq LLM.

    Uses llama-3.1-8b-instant via Groq API as a fast, free-tier LLM.

    Args:
        resume_document (Document): LangChain Document containing resume text.

    Returns:
        str: Summary text generated by the LLM.

    Raises:
        ValueError: If GROQ_API_KEY is not set.
    """
    groq_api_key = os.getenv("GROQ_API_KEY")
    model_name = os.getenv("MODEL_NAME", "llama-3.1-8b-instant")

    if not groq_api_key:
        raise ValueError("GROQ_API_KEY environment variable is not set.")

    llm = ChatGroq(
        model=model_name,
        temperature=0.0,
        groq_api_key=groq_api_key,
    )

    # Build a focused prompt for resume summarization
    prompt = (
        "You are an expert HR assistant. Summarize the following resume in 3-5 bullet points. "
        "Focus on: years of experience, key skills, education, and notable achievements.\n\n"
        f"Resume:\n{resume_document.page_content[:4000]}"  # Stay within token limits
    )

    response = llm.invoke(prompt)
    return response.content


# ---------------------------------------------------------------------------
# Main Streamlit app
# ---------------------------------------------------------------------------
def main():
    """Main entry point for the Streamlit RAG UI."""
    load_dotenv()

    # Validate required env vars at startup
    index_name = os.getenv("PINECONE_INDEX_NAME")
    if not index_name:
        st.error("❌ PINECONE_INDEX_NAME environment variable is not set. Please check your .env file.")
        st.stop()

    pinecone_api_key = os.getenv("PINECONE_API_KEY")
    if not pinecone_api_key:
        st.error("❌ PINECONE_API_KEY environment variable is not set. Please check your .env file.")
        st.stop()

    # Page config
    st.set_page_config(
        page_title="RAG Case Study - Resume Search",
        page_icon="🔍",
        layout="wide"
    )

    # Sidebar
    st.sidebar.title("🔍 RAG Case Study Search")
    st.sidebar.markdown("---")
    st.sidebar.markdown(
        "**Vector Store:** Pinecone  \n"
        "**Embeddings:** HuggingFace (all-MiniLM-L6-v2)  \n"
        f"**LLM:** Groq ({os.getenv('MODEL_NAME', 'llama-3.1-8b-instant')})"
    )
    st.sidebar.markdown("---")

    query = st.sidebar.text_area("📋 Job Description:", "", height=200,
                                  placeholder="Paste a job description here to find matching resumes...")
    no_of_results = st.sidebar.number_input(
        "Number of results:", min_value=1, max_value=10, value=3
    )

    # Main area header
    st.title("📄 RAG Case Study — Resume Search")
    st.write(
        "Search for similar resumes stored in Pinecone and summarize them using the Groq LLM. "
        "Embeddings are generated locally using HuggingFace (no OpenAI required)."
    )

    # Pre-load embeddings once
    embeddings = create_embeddings()

    # Search button
    if st.sidebar.button("🔍 Search", use_container_width=True):
        if not query or query.strip() == "":
            st.sidebar.error("⚠️ Please enter a job description before searching.")
        else:
            try:
                with st.spinner("Searching Pinecone for similar resumes..."):
                    results = search_similar_documents(query, no_of_results, index_name, embeddings)

                if results:
                    st.sidebar.success(f"✅ Found {len(results)} matching resume(s).")

                    for i, (doc, score) in enumerate(results):
                        source = doc.metadata.get("source", "Unknown")
                        file_name = os.path.basename(source)

                        st.sidebar.write(
                            f"**{i + 1}. {file_name}** — Score: `{score:.4f}`"
                        )

                        st.subheader(f"📄 Result {i + 1}: {file_name}")
                        st.caption(f"Source: `{source}` | Similarity Score: `{score:.4f}`")

                        with st.expander("📖 Show Raw Content", expanded=False):
                            st.text(doc.page_content[:2000] + "..." if len(doc.page_content) > 2000 else doc.page_content)

                        with st.expander("🤖 Show AI Summary (Groq)", expanded=True):
                            try:
                                with st.spinner(f"Generating summary with Groq..."):
                                    summary = get_summary_from_llm(doc)
                                st.markdown(summary)
                            except Exception as llm_err:
                                st.warning(f"⚠️ Could not generate summary: {llm_err}")

                        st.divider()
                else:
                    st.sidebar.warning("⚠️ No similar documents found. Try a different query.")
                    st.info("No matching resumes were found for your query. Try refining the job description.")

            except Exception as e:
                st.sidebar.error(f"❌ Search error: {e}")
                st.error(f"An error occurred during search: {e}")
    else:
        st.info("👈 Enter a job description in the sidebar and click **Search** to get started.")


if __name__ == "__main__":
    main()
